### PR TITLE
New metrics: OutputVolts and InternalTemp

### PR DESCRIPTION
**Pull request by neredera**
This PR add two new metrics:
- the output voltage of the UPS
- the internal temperature of the UPS

### CODE REVIEW

**Comment by Pagefreak** [comment]
LGTM please merge

**Comment by fire833** [comment]
Would be great if this could merge.

**Comment by jhron** [comment]
Please merge

**Comment by mdlayher** [comment]
Thanks. I'll rename the temperature metric to fit the usual Prometheus convention.

**Pull request merged**
